# docker-compose run railsvm rails-api new . --force -d postgresql --skip-bundle --skip-test-unit
# docker-compose build
# docker-compose run railsvm rake db:create
# docker-compose run railsvm rake db:migrate
# docker-compose up railsvm
# docker-compose up rake
version: '2'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD
  mongo:
    image: mongo
  railsvm:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mongo
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD
      - MONGO_HOST=mongo:27017
  rake:
    build: .
    command: docker/docker-rake-commands.sh
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mongo
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD
      - MONGO_HOST=mongo:27017
  test:
    build: .
    command: docker/docker-test-commands.sh
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mongo
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD
      - MONGO_HOST=mongo:27017
 
